name: Lint Reference Files
on:
  push:
    branches:
      - master
    paths:
      - 'locale/en/**.ftl'
  pull_request:
    branches:
      - master
    paths:
      - 'locale/en/**.ftl'
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Lint reference
        run: |
          moz-fluent-lint ./locale/en --config .github/linter_config.yml
      - name: Check for unchanged IDs
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
              mkdir old && mkdir new
              diff=$( git diff --name-only ${{ github.event.pull_request.base.sha }} $GITHUB_SHA )
              for file in $diff; do
                git show ${{ github.event.pull_request.base.sha }}:$file > old/$file
                git show $GITHUB_SHA:$file > new/$file
              done
              python ./.github/scripts/unchanged-ids/fluent.syntax/parse_messages_terms_to_dict.py old new
          fi
